# Site settings
title: TECHO | Rosario - Argentina
email: gestiontechorosario@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  ¡Anotate a la próxima construcción!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kevlugli.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  techorosario

# Build settings
markdown: kramdown
